### PR TITLE
kcqrs: allow saving of strings with any length

### LINKED ISSUE #31: kcqrs: allow saving of strings with any size
Datastore has a limitation of 1500 bytes for a field and when try to save strings with 
size bigger of 1500  bytes, the save operation fails.
It should be allowed saving of string with any size.

### PR DESCRIPTION
**Pull request by StanislavaKaukova**
When store aggregate with size bigger of 1500 bytes datastore throw exception.
Now allow save of strings with any size. The entities are saved and get as  text 

closes:  #31

### CODE REVIEW

File: kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt [hunk 1]
```diff
@@ -65,7 +65,7 @@ class AppEngineEventStore(private val kind: String = "Event", private val messag
             }
 
             @Suppress("UNCHECKED_CAST")
-            val aggregateEvents = aggregateEntity.getProperty(eventsProperty) as MutableList<String>
+            val aggregateEvents = aggregateEntity.getProperty(eventsProperty) as MutableList<Any>
```
Comment (georgievJon) [inline kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt]: For me is better to save only Text instead Any and remove check String or Text

File: kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt [hunk 2]
```diff
@@ -229,4 +230,25 @@ class AppEngineEventStore(private val kind: String = "Event", private val messag
...
     private fun aggregateKey(aggregateId: String, aggregateIndex: Long) =
             KeyFactory.createKey(kind, "${aggregateId}_$aggregateIndex")
+
+    private fun stringFormatOr(values: List<String>): List<Any> {
+        val events = mutableListOf<Any>()
+        values.map {
+            if (it.toByteArray(Charsets.UTF_8).size >= 1000) {
+                events.add(Text(it))
+            } else {
+                events.add(it)
```
Comment (georgievJon) [inline kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt]: Every element of list can be "Text". No need to be "String"

File: kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt [hunk 3]
```diff
@@ -229,4 +230,25 @@ class AppEngineEventStore(private val kind: String = "Event", private val messag
...
+            }
+        }
+
+        return events
+    }
+
+    private fun list(values: List<Any>): List<String> {
+        val result = mutableListOf<String>()
+        values.map {
+            result.add(it as? String ?: (it as Text).value)
```
Comment (georgievJon) [inline kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt]: This check can be preserve because already saved event are from type "String"

**Review by georgievJon — CHANGES_REQUESTED** [review]

**Review by georgievJon — APPROVED** [review]

**Review by mlesikov — APPROVED** [review]
